### ISSUE TITLE
Layout items well on the UI

### ISSUE THREAD

**Issue by athmangude** [BrianLusina/street-visum#2]
<img width="1680" alt="screen shot 2017-11-13 at 10 35 36" src="https://user-images.githubusercontent.com/2655082/32714398-af79c10a-c85e-11e7-84fe-494b016a9bec.png">

**Comment by BrianLusina** [comment]
This [commit](https://github.com/BrianLusina/street-visum/commit/d599b4256ce549cf5e3920eff44e4f7970fdc805) fixes alignment of items on the UI
